# Code Coverage check presented by codecov

coverage:
  status:
    patch:                  # only validate the coverage of the PR
      tests:
        target: 95%         # Almost all test code should be executed
        paths: "**/test/"   # only include coverage in "tests/" folder
      new-pr-coverage:
        target: 90%         # new PR should have 90% coverage
        threshold: 0%       # Coverage should not drop by this amount compared against base
        base: auto
        paths: "!**/test/"  # ignore test folders
       # advanced settings
        branches:           # add release branch when spinning off from main 
          - main
        if_ci_failed: error # success, failure, error, ignore
