# Code Coverage check presented by codecov

coverage:
  status:
    project:                  # only validate the coverage of the PR
      default:
        target: 70%         # Almost all test code should be executed
        base: auto