package com.flipkart.grayskull.mappers;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a mapper interface as generated by MapStruct. This annotation is used
 * to exclude the generated mapper from being processed by JaCoCo coverage tool.
 */
@Retention(RetentionPolicy.CLASS)
@Target(ElementType.TYPE)
public @interface GeneratedMapper {
}
