name: Publish Server to Maven Central

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          server-id: ossrh
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN

      - name: Import GPG key
        run: echo "${{ secrets.FOSS_GPG_KEY }}" | gpg --batch --import

      - name: Build and Deploy
        run: |
          ./mvnw -B -pl '!simple-app' -Prelease clean deploy \
            -DskipTests \
            -Dgpg.passphrase=${{ secrets.FOSS_GPG_PASSPHRASE }}
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
